#
# The %w and %W operators make it difficult to use comments in-line
# with configuration arrays.  This is inexplicably recommended by old
# versions of rubocop.
#
# Here, we explicitly disable the check, so that we may freely use []
# instead of %w().
#
Style/WordArray:
  Enabled: false

# This cop is too noisy for use in our current codebase.
Metrics/MethodLength:
  Enabled: false